### PR TITLE
Lithuanian translation improved

### PR DESCRIPTION
**Pull request by mauglee**

### CODE REVIEW

**Comment by mauglee** [comment]
Travis [failed](https://travis-ci.org/tinuzz/wp-plugin-trackserver/jobs/344554703) for PHP 5.6, But "errors" are not in my files. You can pull as is, or fix your code, then I will pull-request again.

**Comment by tinuzz** [comment]
Hi Dainius,

Thank you. I merged your PR and will make a new Trackserver release soon.

For the future, how do you feel about translating via  WordPress' online translation system? See

https://translate.wordpress.org/projects/wp-plugins/trackserver/dev/lt/default

I have imported your .po file, and the translated strings now have the status 'Waiting', meaning someone called a _translation editor_ should approve the translations. I could also request for you to be a translation editor for Trackserver, for Lithuanian, so you could approve the translations yourself.

Let me know what you think.

Best regards,
Martijn.

**Comment by mauglee** [comment]
Hi, Martijn,
 
> For the future, how do you feel about translating via  WordPress'
> online translation system? See
> 
> https://translate.wordpress.org/projects/wp-plugins/trackserver/dev/lt/default

for translations I use poedit https://poedit.net/ which scans code
directly. But web-based solution should be ok too. And I think it will
be better for you if someone else wants to contribute translations.

> I could also request for you to be a translation editor for
> Trackserver, for Lithuanian 

ok, let's try

-- 
Da

**Comment by tinuzz** [comment]
Yup, I use poedit myself. I think the benefit of online translation is, that I don't have to pull the translations to release them. The drawback is, that you can only translate _after_ release, because it works on the latest released version of the plugin.  On Github, you would be able to follow development and translate new strings _before_ the release.

I'm not sure what's best. If you prefer just pulling trackserver.pot from Github and sending PRs, I'm fine with that.

**Comment by mauglee** [comment]
> I'm not sure what's best. If you prefer just pulling trackserver.pot
> from Github and sending PRs, I'm fine with that.

I am not familiar with online translator, but when locally poedit'ing,
I can quickly jump to source and see context where the string appears.
Also poedit has „Fuzzy“ functionality.
We can stay with git.

-- 
Da

**Comment by tinuzz** [comment]
Perfect ;-)

Will you keep track of the changes yourself, I do you need a shout when there is an update?

**Comment by mauglee** [comment]
> Will you keep track of the changes yourself, I do you need a shout
> when there is an update?

a „shout“ would be good :)

-- 
Da

**Comment by tinuzz** [comment]
OK!

**Comment by mauglee** [comment]
> OK!

I also clicked Watch on your repo.

-- 
Da

**Pull request merged**
