### PR TITLE
Lithuanian translation added

### PR DESCRIPTION
**Pull request by mauglee**

### CODE REVIEW

**Comment by tinuzz** [comment]
Thank you! I will merge it as soon as possible.

**Comment by mauglee** [comment]
I personally use your plugin only in English, but I want to contribute you :)
I am programmer and have decided to write some software to collect live tracking data from Osmand app and to visualize it on map. Before goin' on, I made some research „what's already done“. And I have found your plugin, which is amazing as does everything I need. You saved me a lot of work, so I want to help you somehow. So here my 2 cents go. This is the beauty of opensource.

**Comment by tinuzz** [comment]
Hello Mauglee,

I just pushed a new version of the POT file with some new strings for upcoming features. Would you consider updating the Lithuanian translation with the new strings?

Thank you,
Martijn.

**Comment by mauglee** [comment]
Hi,

> Hello Mauglee,

this is my nickname (and username on git). My real name is Dainius. But
that's ok, a lot of friends call me Mauglee.

> Would you consider updating the Lithuanian translation with the new
> strings? 

I am translating right now. It is hard enough without knowing context
and translate such a therms like „Geofencing“. But I'll do my best :)

-- 
Da

**Pull request merged**
